language: python

python:
    - "3.8"
env:
    - SECRET_KEY="this*is*a*secretkey"

install:
    - pip3 install -r requirements.txt

script:
    - python3 manage.py makemigrations
    - pyhton3 manage.py migrate
