language: python

python:
    - "3.9"
env:
    - SECRET_KEY='bxf5\{\(\{\ghjvmn\}\<\>\vyghvjh143376870x9xaeAA19x8x08fbx8exb7xdbxd2rx15Exa21'

install:
    - pip3 install -r requirements.txt

script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
