# Generated by Django 3.1.2 on 2020-11-26 07:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_date', models.DateTimeField()),
                ('destination_date', models.DateTimeField()),
                ('duration', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=1000)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitality', models.CharField(choices=[('E', 'Economy Class'), ('B', 'Bussiness Class'), ('A', 'First Class')], max_length=1)),
                ('seat', models.CharField(choices=[('A', 'Aisle'), ('M', 'Middle'), ('W', 'Window')], default='M', max_length=1)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='flights.flight')),
                ('food', models.ManyToManyField(blank=True, related_name='cusines', to='flights.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=21)),
                ('last', models.CharField(max_length=21)),
                ('age', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Not Prefered to say')], default='X', max_length=1)),
                ('email', models.EmailField(default='hard@mail.co', max_length=254)),
                ('ph_no', models.BigIntegerField(blank=True, null=True)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='flights.Flight')),
                ('tickets', models.ManyToManyField(blank=True, related_name='journeys', to='flights.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='flights.ticket')),
            ],
        ),
    ]
