# Generated by Django 3.0.6 on 2020-10-10 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20200514_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='ph_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Not Prefered to say')], default='X', max_length=1),
        ),
    ]
