# Generated by Django 3.0.6 on 2020-10-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20201010_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('hospitality', models.CharField(choices=[('E', 'Economy')], max_length=1)),
            ],
        ),
    ]
