# Generated by Django 3.1.2 on 2020-11-30 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='capacity',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
