# Generated by Django 3.0.6 on 2020-10-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Not Prefered to say')], default='Male', max_length=1),
        ),
    ]
