# Generated by Django 3.1.2 on 2021-02-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20210214_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Not Preferred to say')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='food',
            field=models.ManyToManyField(blank=True, related_name='cuisines', to='flights.Food'),
        ),
    ]
