# Generated by Django 3.1.2 on 2020-11-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_remove_flight_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='destination_date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='origin_date',
        ),
    ]
