# Generated by Django 3.0.6 on 2020-10-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_auto_20201012_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ph_no',
            field=models.IntegerField(blank=True),
        ),
    ]
