# Generated by Django 3.1.2 on 2020-12-21 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0008_bridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridge',
            name='user_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ph_no',
            field=models.BigIntegerField(blank=True),
        ),
    ]
