# Generated by Django 3.0.6 on 2020-10-12 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_auto_20201012_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ph_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Not Prefered to say')], default='X', max_length=1),
        ),
    ]
