# Generated by Django 3.1.2 on 2020-12-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_auto_20201221_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='ph_no',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
