# Generated by Django 3.0.6 on 2020-10-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_auto_20201012_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ph_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
