# Generated by Django 3.0.6 on 2020-10-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_auto_20201013_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hospitality',
            field=models.CharField(choices=[('E', 'Economy'), ('B', 'Bussiness')], max_length=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='food',
            field=models.ManyToManyField(blank=True, related_name='cusines', to='flights.Food'),
        ),
    ]
