# Generated by Django 3.1.2 on 2020-12-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_auto_20201221_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='passengers',
            field=models.ManyToManyField(related_name='relatives', to='flights.Passenger'),
        ),
    ]
