# Generated by Django 3.0.6 on 2020-10-13 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_auto_20201013_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.CharField(choices=[('A', 'Aisle'), ('M', 'Middle'), ('W', 'Window')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hospitality',
            field=models.CharField(choices=[('E', 'Economy-Class'), ('B', 'Bussiness-Class'), ('A', 'First-Class')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
