# Generated by Django 3.0.6 on 2020-10-15 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_auto_20201013_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='journeys', to='flights.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
