# Generated by Django 3.1.2 on 2020-10-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_auto_20201015_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='hospitality',
            field=models.CharField(choices=[('E', 'Economy Class'), ('B', 'Bussiness Class'), ('A', 'First Class')], max_length=1),
        ),
    ]
