# Generated by Django 3.1.2 on 2020-10-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0015_auto_20201021_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='origin_date',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(default='user@mail.co', max_length=254),
        ),
    ]
