# Generated by Django 3.1.2 on 2020-10-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0016_auto_20201021_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='ph_no',
            field=models.BigIntegerField(),
        ),
    ]
