# Generated by Django 3.1.2 on 2020-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0018_auto_20201021_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='origin_date',
            field=models.DateTimeField(),
        ),
    ]
